-- Enable the pgvector extension so PostgreSQL can store and compare vector embeddings.
-- "IF NOT EXISTS" prevents an error if it's already been enabled.
CREATE EXTENSION IF NOT EXISTS vector;

-- Drop the table if it already exists so this script can be re-run cleanly
-- without hitting a "table already exists" error.
DROP TABLE IF EXISTS exercises;

CREATE TABLE exercises (
    -- Unique identifier from the CSV (e.g. "EX_001"). Used as the primary key
    -- so we never accidentally insert the same exercise twice.
    id            TEXT PRIMARY KEY,

    title         TEXT NOT NULL,
    description   TEXT,
    tags          TEXT,
    body_part     TEXT,
    difficulty    TEXT,
    equipment     TEXT,
    injury_focus  TEXT,
    intensity     TEXT,

    -- 384-dimensional vector generated by the sentence-transformers model.
    -- This is what pgvector uses to find semantically similar exercises
    -- when a user submits a query.
    embedding     vector(384)
);